- name: Download CloudWatch Agent installer
  get_url:
    url: https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb
    dest: ./amazon-cloudwatch-agent.deb
    mode: '0644'

- name: Install CloudWatch Agent
  shell: sudo dpkg -i -E ./amazon-cloudwatch-agent.deb

- name: Copy config file
  template:
    src: ../files/cloudwatchagent.json
    dest: /home/ubuntu/config.json

- name: Moving config
  shell: sudo mv /home/ubuntu/config.json /opt/aws/amazon-cloudwatch-agent/etc

- name: Add CloudWatch Agent user to docker group
  user:
    name: cwagent
    groups: docker
    append: yes`

- name: Enable CloudWatch Agent service
  systemd:
    name: amazon-cloudwatch-agent
    enabled: yes
    state: restarted

- name: Start CloudWatch Agent
  command: >
    /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl
    -a fetch-config
    -m ec2
    -s
    -c file:/opt/aws/amazon-cloudwatch-agent/etc/config.json